### ISSUE TITLE
求助大佬

### ISSUE THREAD

**Issue by MuTou-fs** [xjy37-me/OpenCore-EFI-ASUS#1]
大佬我的主板和你一样，但是显卡注入要加device-id属性  不然会黑屏
再次尝试就会卡在<Error>failed to bootstrap path:……

**Comment by xjy37-me** [comment]
## 重要
请把机型提一下，带上CPU以及核心显卡型号。如ASUS N552VW ，i7-6700HQ，HD530。


## 回答
> 关于卡在log，我们分为boot issue，为启动早期卡住；kernel issue，为内核issue，出现在boot issue之后的时间。卡在哪一般不是刚好出问题，而是之上的某个语句

你提到的应该是显卡相关，可使用whatevergreen，某些显卡是需要注入特定device-id的如KabyLake平台的UHD 620

## 其他
> + 可以提一下你目前在安装的哪个阶段。
> + 可以看我写的[OC-Patch-Wiki(未完善)](https://gitee.com/Sirius2/OC-Patch-Wiki)

## 联系
直接提issue或者[发邮件](mailto:xjy37-me@outlook.com)
